#!/usr/bin/env python
import argparse
import os
import pkg_resources
import yaml
from mako.template import Template
resource_package = 'pycon'

resource_path_stub = os.path.join('templates','stub.mako')
stub_template_string = pkg_resources.resource_string(resource_package, resource_path_stub)
stub_template = Template(stub_template_string)

p = argparse.ArgumentParser()
# Required Positional Arguments
p.add_argument('method', help="soslasso, iterlasso, lasso, searchlight. ToDo: searchlightrsa, nrsa")
# Flags
p.add_argument('-v','--verbose',action='store_true',help="Print parameter details into the stub file as comments.")
# Options
p.add_argument('-m','--metadata',type=str,default='',help="Path to metadata file.")
p.add_argument('-d','--data',type=str,nargs='+',default=['/path/to/data/s101.mat','/path/to/data/s102.mat'],help='List of paths to include in the data list.')

args = p.parse_args()

stub_text = stub_template.render(method=args.method, data=args.data, metadata=args.metadata, verbose=args.verbose)
print stub_text
