<%page args="UNIQUE,JOBDIR,SUBMITFILE,PRESCRIPT='',POSTSCRIPT=''" cached="True" cache_type="memory"/>
JOB ${UNIQUE} ${SUBMITFILE} ${JOBDIR}
% if PRESCRIPT:
SCRIPT PRE ${UNIQUE} ${PRESCRIPT}
% endif
% if POSTSCRIPT:
SCRIPT POST ${UNIQUE} ${POSTSCRIPT}
% endif
RETRY ${UNIQUE} 10
